services:
  - type: web
    name: mylove-mood-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:flask_app
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
    plan: free